name = "tg-o2o-bot-v1"
main = "worker.js"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "ba9623d508704ab8bebcfa93973dba91" }
]

compatibility_flags = [ "nodejs_compat" ]

[env.production]
vars = { BOT_CONFIGS = "[]" }
