name = "tg-o2o-bot-v1"
main = "worker.js"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "" }
]

compatibility_flags = [ "nodejs_compat" ]

[env.production]
vars = { BOT_CONFIGS = "[]" }
